namespace RiftBoundTracker.App.Services.PlayOnline;

public sealed class MatchPlayer
{
    public required string ConnectionId { get; set; }
    public required string Name { get; init; }
    public bool IsHost { get; init; }
    public int? DeckId { get; set; }
    public bool Ready { get; set; }
}

/// <summary>
/// One player's zones. Hand is private by design - PublicView() below is what actually enforces
/// that, never the client. Board/Battlefield/Trash/Banishment are public zones every player can
/// see in full, matching how those zones actually work in Riftbound.
/// </summary>
public sealed class PlayerZones
{
    // Face-down and never sent to any client, including their own owner - order is Secret
    // Information per Core Rule 108.4.d/108.5.d, and only Draw/Channel are allowed to touch them.
    public List<string> MainDeck { get; } = [];
    public List<string> RuneDeck { get; } = [];
    public List<string> Hand { get; } = [];
    // Board is this player's own Base (Core Rule 107.1.d) - private to their control, tracking
    // per-object state (Ready/Exhausted) since several Keywords check or change it and two copies
    // of the same-named unit need to be distinguishable, which a plain List<string> can't do.
    // "At a Battlefield" is NOT here - see BoardState.Battlefields below.
    public List<UnitInstance> Board { get; } = [];
    // The 3 candidates dealt at Setup, before the player has chosen one - Secret Information until
    // chosen (only the owner should see what their unchosen options were), cleared once chosen.
    // See MatchRoomService.SelectBattlefield, which moves the pick into BoardState.Battlefields.
    public List<string> BattlefieldChoices { get; } = [];
    public List<string> Trash { get; } = [];
    public List<string> Banishment { get; } = [];
    // Channeled runes sitting in this player's Base - Public Information per Core Rule 107.1.d.
    // This is NOT the Rune Pool (Core Rule 165/166): the Pool is a conceptual numeric amount of
    // Energy/Power, generated by exhausting or recycling a Base rune, tracked in Counters below
    // ("Energy"/"Power") alongside any player-added counter like Life - not a separate card zone.
    public List<string> Base { get; } = [];
    // How many of Base's runes have already been tapped for Energy this turn (Core Rule 164.2.a's
    // "[E]: Add [1]" - only usable once before the rune readies again). Reset every Awaken Phase.
    public int ExhaustedRuneCount { get; set; }
    public string? LegendCardId { get; set; }
    public string? ChampionCardId { get; set; }
    public int Score { get; set; } // Conquer/Hold points
    public Dictionary<string, int> Counters { get; } = [];
}

/// <summary>
/// One Battlefield actually in play this game (Core Rule 486.5: "The selected Battlefields are
/// placed simultaneously in the Battlefield Zone" - singular, shared zone, not one per player).
/// Keyed by which player picked it (OwnerConnectionId) since Core Rule 486.4 gives 1v1 exactly one
/// Battlefield per player (Battlefield Count: 2) - that's a stable, unambiguous address for it, and
/// simpler than inventing a separate slot id. Units from EITHER player can be Units here at once;
/// each tracks its own ControllerConnectionId since list membership alone can't say whose it is
/// anymore the way PlayerZones.Board's list membership still does.
/// </summary>
public sealed class BattlefieldSlot
{
    public required string CardId { get; init; }
    public required string OwnerConnectionId { get; init; }
    public List<UnitInstance> Units { get; } = [];
}

public sealed class BoardState
{
    public int TurnNumber { get; set; } = 1;
    public string? ActivePlayerConnectionId { get; set; }
    public Dictionary<string, PlayerZones> ZonesByPlayer { get; } = [];
    public List<BattlefieldSlot> Battlefields { get; } = [];

    public PlayerZones GetOrAddZones(string connectionId) =>
        ZonesByPlayer.TryGetValue(connectionId, out var zones) ? zones : ZonesByPlayer[connectionId] = new PlayerZones();
}

/// <summary>
/// A room this host instance is running, entirely in memory - nothing here is persisted, matching
/// the plan's explicit "nothing persistent between sessions" scope. One host process can run more
/// than one room in principle, but Phase 1's UI only ever creates/joins a single active one.
/// </summary>
public sealed class MatchRoom
{
    public required string RoomCode { get; init; }
    public required string HostConnectionId { get; set; }
    public List<MatchPlayer> Players { get; } = [];
    public BoardState Board { get; } = new();
    public DateTimeOffset CreatedAt { get; } = DateTimeOffset.UtcNow;
    // A plain-English feed of what's happened, newest last - purely a convenience log, not itself
    // game state. Capped so a long match doesn't grow this without bound.
    public List<LogEntry> Log { get; } = [];

    public const int MaxPlayers = 3; // host + 2 friends, per the plan's explicit "just me and two friends" scope
    public const int MaxLogEntries = 200;
}

public sealed record LogEntry(DateTimeOffset At, string Message);

/// <summary>A specific unit sitting on the Board or at a Battlefield - Core Rule 415 (Ready) / 416's
/// neighborhood. Exhausted is the one piece of real per-object state Phase 2 tracks so far; more
/// Keywords need more state than this (Assault's Attacker designation, Shield's counter, Attach
/// relationships...), added as each is actually built rather than speculatively up front.</summary>
public sealed class UnitInstance
{
    public required string InstanceId { get; init; }
    public required string CardId { get; init; }
    // Redundant while sitting in PlayerZones.Board (list membership already says whose it is), but
    // required once a unit is at a shared Battlefield (BoardState.Battlefields), where units from
    // both players can sit in the same list. Set on every unit regardless of zone, for one uniform
    // "whose is this" check everywhere instead of two different rules depending on zone.
    public required string ControllerConnectionId { get; init; }
    public bool Exhausted { get; set; }
    // Core Rule 142: Damage is a marked value, not a permanent reduction to Might - it's compared
    // against the unit's Might to check Lethal Damage (142.4.a), and heals off at specific times
    // (143.3.b), it doesn't subtract from Might directly.
    public int Damage { get; set; }
    // Core Rules 717-719 (Attachment): a Gear attached to a unit is still its own object in the
    // same zone list, just linked to a "Top-Most Card" - null means this instance isn't Attached to
    // anything (it may still be a Top-Most Card that other instances point at). Detaching (the
    // target leaving the board, rule 719.5) is handled wherever an instance leaves Board/Battlefield.
    public string? AttachedToInstanceId { get; set; }
}
