namespace RiftBoundTracker.App.Services;

public sealed record PremadePackCardEntry(string SetId, string Code, int Quantity);
public sealed record PremadePackDefinition(string Key, string Name, string Wave, List<PremadePackCardEntry> Cards);

/// <summary>
/// Hand-curated contents of official preconstructed "Champion Deck" / "Proving Grounds" products,
/// so someone who buys one physically can add its exact contents to their tracked collection in
/// one action instead of looking up and incrementing every card by hand.
///
/// Sourced from user-supplied exports of the physical product's card list, each line giving an
/// exact SetId-CollectorCode — deliberately NOT card names, since names are ambiguous (comma vs.
/// dash separators, multiple prints sharing a name, punctuation variants) in a way an exact code
/// isn't. PremadePackImportService resolves each entry via CardCacheService.FindByCodeAsync, the
/// same exact-code lookup deck import uses for RiftKeep-format lines — a code that doesn't resolve
/// to exactly one card surfaces as unmatched rather than silently guessing.
///
/// The original playriftbound.com announcements for the three Origins Champion Decks (Viktor,
/// Jinx, Lee Sin) have since been retired from the site and aren't reachable through any source
/// this app is willing to fetch (the third-party sites that still list them block AI/Claude access
/// via robots.txt) — these three and the four Proving Grounds decks were transcribed by hand from
/// the physical product. The Vendetta/Unleashed Champion Decks (Shen, Zed, Vex) were instead
/// sourced from user-supplied RiftAtlas deck codes, decoded via RiftAtlasDeckCodeService and
/// cross-checked against the card catalog — same exact-code data, different origin.
/// </summary>
public static class PremadePackCatalogService
{
    public static readonly List<PremadePackDefinition> Packs =
    [
        new("origins-viktor", "Viktor Champion Deck", "Origins", [
            new("OGN", "265", 1),
            new("OGN", "118", 1),
            new("OGN", "294", 1),
            new("OGN", "293", 1),
            new("OGN", "275", 1),
            new("OGN", "233", 1),
            new("OGN", "222", 3),
            new("OGN", "216", 3),
            new("OGN", "214", 6),
            new("OGN", "213", 2),
            new("OGN", "209", 3),
            new("OGN", "208", 3),
            new("OGN", "206", 2),
            new("OGN", "083", 2),
            new("OGN", "117", 1),
            new("OGN", "111", 1),
            new("OGN", "103", 3),
            new("OGN", "101", 2),
            new("OGN", "095", 2),
            new("OGN", "094", 2),
            new("OGN", "093", 2),
            new("OGN", "090", 2),
            new("OGN", "089", 6),
            new("OGN", "086", 2),
            new("OGN", "084", 3),
        ]),
        new("origins-jinx", "Jinx Champion Deck", "Origins", [
            new("OGN", "251", 1),
            new("OGN", "166", 6),
            new("OGN", "298", 1),
            new("OGN", "289", 1),
            new("OGN", "285", 1),
            new("OGN", "195", 1),
            new("OGN", "185", 3),
            new("OGN", "182", 3),
            new("OGN", "180", 2),
            new("OGN", "178", 2),
            new("OGN", "169", 3),
            new("OGN", "168", 3),
            new("OGN", "001", 2),
            new("OGN", "165", 2),
            new("OGN", "036", 1),
            new("OGN", "030", 1),
            new("OGN", "024", 2),
            new("OGN", "019", 3),
            new("OGN", "011", 1),
            new("OGN", "008", 2),
            new("OGN", "007", 6),
            new("OGN", "006", 3),
            new("OGN", "003", 3),
            new("OGN", "002", 3),
        ]),
        new("origins-lee-sin", "Lee Sin Champion Deck", "Origins", [
            new("OGN", "257", 1),
            new("OGN", "135", 2),
            new("OGN", "289", 1),
            new("OGN", "282", 1),
            new("OGN", "280", 1),
            new("OGN", "157", 1),
            new("OGN", "152", 1),
            new("OGN", "151", 1),
            new("OGN", "147", 3),
            new("OGN", "142", 2),
            new("OGN", "137", 2),
            new("OGN", "136", 3),
            new("OGN", "042", 6),
            new("OGN", "132", 3),
            new("OGN", "128", 3),
            new("OGN", "126", 6),
            new("OGN", "125", 2),
            new("OGN", "065", 3),
            new("OGN", "060", 1),
            new("OGN", "058", 3),
            new("OGN", "055", 3),
            new("OGN", "053", 2),
            new("OGN", "052", 3),
            new("OGN", "043", 2),
        ]),
        new("unleashed-vi", "Vi Champion Deck", "Unleashed", [
            new("UNL", "187", 1),
            new("OGN", "036", 1),
            new("UNL", "002", 3),
            new("SFD", "009", 2),
            new("UNL", "006", 2),
            new("UNL", "008", 2),
            new("UNL", "010", 2),
            new("UNL", "012", 2),
            new("UNL", "015", 2),
            new("UNL", "017", 2),
            new("UNL", "018", 2),
            new("UNL", "153", 2),
            new("UNL", "154", 2),
            new("UNL", "156", 2),
            new("UNL", "161", 2),
            new("UNL", "163", 2),
            new("UNL", "176", 2),
            new("UNL", "001", 1),
            new("UNL", "009", 1),
            new("UNL", "024", 1),
            new("UNL", "026", 1),
            new("UNL", "030", 1),
            new("UNL", "159", 1),
            new("UNL", "175", 1),
            new("UNL", "188", 1),
            new("UNL", "215", 1),
            new("UNL", "217", 1),
            new("UNL", "218", 1),
            new("VEN", "R01", 6),
            new("VEN", "R06", 6),
        ]),
        new("spiritforged-fiora", "Fiora Champion Deck", "Spiritforged", [
            new("SFD", "205", 1),
            new("SFD", "110", 1),
            new("SFD", "095", 3),
            new("SFD", "107", 3),
            new("SFD", "108", 3),
            new("SFD", "161", 3),
            new("OGN", "136", 2),
            new("OGN", "229", 2),
            new("SFD", "093", 2),
            new("SFD", "097", 2),
            new("SFD", "099", 2),
            new("SFD", "103", 2),
            new("SFD", "106", 2),
            new("SFD", "113", 2),
            new("SFD", "156", 2),
            new("SFD", "157", 2),
            new("SFD", "167", 2),
            new("SFD", "110", 1),
            new("SFD", "116", 1),
            new("SFD", "172", 1),
            new("SFD", "180", 1),
            new("SFD", "206", 1),
            new("SFD", "213", 1),
            new("SFD", "218", 1),
            new("SFD", "221", 1),
            new("OGN", "126", 6),
            new("OGN", "214", 6),
        ]),
        new("proving-grounds-annie", "Annie Proving Grounds Deck", "Origins: Proving Grounds", [
            new("OGS", "017", 1),
            new("OGN", "185", 3),
            new("OGS", "018", 2),
            new("OGS", "011", 2),
            new("OGS", "010", 2),
            new("OGS", "003", 3),
            new("OGS", "002", 3),
            new("OGS", "001", 2),
            new("OGN", "296", 1),
            new("OGN", "191", 3),
            new("OGN", "005", 3),
            new("OGN", "176", 3),
            new("OGN", "174", 3),
            new("OGN", "171", 3),
            new("OGN", "170", 3),
            new("OGN", "169", 3),
            new("OGN", "166", 6),
            new("OGN", "013", 2),
            new("OGN", "007", 6),
        ]),
        new("proving-grounds-garen", "Garen Proving Grounds Deck", "Origins: Proving Grounds", [
            new("OGS", "023", 1),
            new("OGN", "215", 2),
            new("OGS", "024", 2),
            new("OGS", "016", 3),
            new("OGS", "015", 3),
            new("OGS", "013", 2),
            new("OGS", "007", 2),
            new("OGN", "294", 1),
            new("OGN", "222", 3),
            new("OGN", "219", 3),
            new("OGN", "126", 6),
            new("OGN", "214", 6),
            new("OGN", "211", 3),
            new("OGN", "210", 3),
            new("OGN", "206", 3),
            new("OGN", "132", 3),
            new("OGN", "131", 2),
            new("OGN", "130", 3),
            new("OGN", "129", 3),
        ]),
        new("proving-grounds-lux", "Lux Proving Grounds Deck", "Origins: Proving Grounds", [
            new("OGS", "021", 1),
            new("OGN", "210", 3),
            new("OGS", "022", 2),
            new("OGS", "016", 3),
            new("OGS", "014", 2),
            new("OGS", "012", 3),
            new("OGS", "006", 2),
            new("OGN", "288", 1),
            new("OGN", "219", 3),
            new("OGN", "214", 6),
            new("OGN", "084", 2),
            new("OGN", "206", 3),
            new("OGN", "105", 3),
            new("OGN", "103", 3),
            new("OGN", "095", 3),
            new("OGN", "089", 6),
            new("OGN", "088", 2),
            new("OGN", "087", 3),
            new("OGN", "085", 3),
        ]),
        new("proving-grounds-master-yi", "Master Yi Proving Grounds Deck", "Origins: Proving Grounds", [
            new("OGS", "019", 1),
            new("OGN", "134", 3),
            new("OGS", "020", 2),
            new("OGS", "009", 2),
            new("OGS", "008", 3),
            new("OGS", "005", 3),
            new("OGS", "004", 2),
            new("OGN", "279", 1),
            new("OGN", "142", 2),
            new("OGN", "137", 3),
            new("OGN", "042", 6),
            new("OGN", "129", 2),
            new("OGN", "127", 3),
            new("OGN", "126", 6),
            new("OGN", "055", 3),
            new("OGN", "052", 3),
            new("OGN", "049", 3),
            new("OGN", "048", 3),
            new("OGN", "046", 3),
        ]),
        new("vendetta-shen", "Shen Champion Deck", "Vendetta", [
            new("VEN", "147", 1),
            new("OGN", "042", 6),
            new("OGN", "214", 6),
            new("VEN", "028", 3),
            new("VEN", "117", 3),
            new("OGN", "043", 2),
            new("OGN", "058", 2),
            new("UNL", "156", 2),
            new("VEN", "026", 2),
            new("VEN", "027", 2),
            new("VEN", "030", 2),
            new("VEN", "033", 2),
            new("VEN", "042", 2),
            new("VEN", "119", 2),
            new("VEN", "123", 2),
            new("VEN", "128", 2),
            new("VEN", "129", 2),
            new("OGN", "241", 1),
            new("OGN", "280", 1),
            new("VEN", "031", 1),
            new("VEN", "034", 1),
            new("VEN", "043", 1),
            new("VEN", "116", 1),
            new("VEN", "126", 1),
            new("VEN", "127", 1),
            new("VEN", "135", 1),
            new("VEN", "138", 1),
            new("VEN", "148", 1),
            new("VEN", "159", 1),
            new("VEN", "166", 1),
        ]),
        new("vendetta-zed", "Zed Champion Deck", "Vendetta", [
            new("VEN", "143", 1),
            new("OGN", "007", 6),
            new("OGN", "166", 6),
            new("VEN", "002", 3),
            new("VEN", "007", 3),
            new("VEN", "008", 3),
            new("VEN", "013", 3),
            new("VEN", "093", 3),
            new("VEN", "095", 3),
            new("VEN", "096", 3),
            new("OGN", "185", 2),
            new("VEN", "012", 2),
            new("VEN", "014", 2),
            new("VEN", "101", 2),
            new("VEN", "105", 2),
            new("VEN", "112", 2),
            new("OGN", "298", 1),
            new("VEN", "017", 1),
            new("VEN", "020", 1),
            new("VEN", "023", 1),
            new("VEN", "102", 1),
            new("VEN", "106", 1),
            new("VEN", "110", 1),
            new("VEN", "144", 1),
            new("VEN", "165", 1),
            new("VEN", "166", 1),
        ]),
        new("unleashed-vex", "Vex Champion Deck", "Unleashed", [
            new("UNL", "193", 1),
            new("VEN", "R02", 6),
            new("VEN", "R05", 6),
            new("UNL", "040", 3),
            new("UNL", "041", 3),
            new("UNL", "042", 3),
            new("UNL", "031", 2),
            new("UNL", "034", 2),
            new("UNL", "036", 2),
            new("UNL", "038", 2),
            new("UNL", "039", 2),
            new("UNL", "047", 2),
            new("UNL", "048", 2),
            new("UNL", "127", 2),
            new("UNL", "133", 2),
            new("UNL", "134", 2),
            new("SFD", "146", 1),
            new("UNL", "035", 1),
            new("UNL", "043", 1),
            new("UNL", "050", 1),
            new("UNL", "052", 1),
            new("UNL", "055", 1),
            new("UNL", "126", 1),
            new("UNL", "136", 1),
            new("UNL", "141", 1),
            new("UNL", "150", 1),
            new("UNL", "194", 1),
            new("UNL", "207", 1),
            new("UNL", "213", 1),
            new("UNL", "214", 1),
        ]),
    ];
}
