using System.Text;
using System.Text.Json;
using LLama;
using LLama.Common;
using LLama.Sampling;
using LLama.Transformers;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using RiftBoundTracker.App.Data;

namespace RiftBoundTracker.App.Services.Rules;

/// <summary>
/// The model orchestrates real lookups instead of reasoning from a single evidence dump it was
/// handed once — closer to how Claude Code itself uses tools than to the single-pass "here's some
/// evidence, write an answer" shape everything else in this file uses.
///
/// Why this exists: four rounds of fine-tuning a model specifically on the adjudicate/explain task
/// shape never got reliability past a real ceiling (see RulesAnswerService's own comment on
/// AdjudicationPipelineEnabled) — and directly probing the RESIDENT fine-tuned model against a
/// simple tool-call prompt showed it doesn't attempt one at all; it just answers as if the tool
/// didn't exist, ignoring the instruction outright. Probing the RAW, un-fine-tuned base model with
/// the identical prompt got a correctly-formed tool call on the first try. The narrow single-pass
/// fine-tuning didn't fail to teach tool use — it measurably destroyed general instruction-following
/// the base model already had. This provider is built against that raw base model specifically, not
/// the fine-tuned "ask-rules-model-v1" LocalLlmExplanationProvider uses — RulesCuratedRulingService
/// already covers the highest-value known questions with zero model involvement; this is for
/// whatever that lookup table doesn't cover, and the model's job here is choosing which real lookup
/// to run and reading its result, not memorizing rules content into its own weights.
///
/// Tools are read-only, deterministic C# calls (RulesSearchService, card/legality/errata lookups) —
/// the model can misuse a tool (wrong argument, no useful match) but it cannot fabricate what a
/// tool returns, since the returned text is never generated by the model itself.
/// </summary>
public sealed class RulesToolAgentProvider(
    RulesLocalAiSettingsService settings, LocalAiModelService modelService,
    IServiceScopeFactory scopeFactory, ILogger<RulesToolAgentProvider> logger) : IDisposable
{
    private const string SystemPrompt = """
        You are a rules assistant for the Riftbound trading card game. You do not know Riftbound's
        rules or cards from memory — you must use tools to look them up before answering. Never
        state a rule, a card's text, or a card's legality unless a tool result just told you it.

        Tools:
        - search_rules(query): searches the official rules by rule number, keyword, or free text.
          Returns matching rules with their number, title, and full text.
        - search_cards(name): looks up a card by name. Returns its printed text, current format
          legality, and any official errata.

        To call a tool, output ONLY this, nothing else:
        <tool_call>{"name": "search_rules", "arguments": {"query": "..."}}</tool_call>

        Call as many tools as you need, one at a time — you'll see each result before deciding
        whether to call another. Once you have enough to answer, respond in plain language with no
        tool_call tag. If your tools turn up nothing relevant after a real attempt, say so plainly
        instead of guessing.

        Your final answer must be a faithful summary of the ACTUAL text inside the most recent
        <tool_response> tags — reread it before you answer. Do not bring in details, examples, or
        other card/rule names from outside that text, even ones that sound related or that you
        recall from earlier in this conversation. If the tool_response doesn't fully answer the
        question, say what it does say and note the gap — never fill it from memory.
        """;

    // Forces round 0's output into exactly the tool-call shape — see the Grammar assignment at the
    // call site for why: real testing caught this model answering from outside-game knowledge on
    // the very first turn despite the system prompt's explicit instruction, so the first lookup is
    // made structurally mandatory rather than merely requested. Doesn't try to pin the argument key
    // to each tool's exact expected name (search_rules wants "query", search_cards wants "name") —
    // RunToolAsync already validates that and returns a plain-text error the model sees as a normal
    // tool result if it gets it wrong, which is a cheap enough recovery path not to need a stricter,
    // more brittle per-tool grammar for round 0 specifically.
    private const string ForcedToolCallGrammar = """
        root ::= "<tool_call>{\"name\": \"" toolname "\", \"arguments\": {\"" argkey "\": \"" argvalue "\"}}</tool_call>"
        toolname ::= "search_rules" | "search_cards"
        argkey ::= [a-zA-Z_]+
        argvalue ::= [^"\n]+
        """;

    private readonly SemaphoreSlim _gate = new(1, 1);
    private ModelParams? _modelParams;
    private LLamaWeights? _weights;
    private string? _loadedModelPath;
    private string? _failedModelPath;

    public bool IsConfigured => settings.IsEnabled() && FindModelPath() is { } path && path != _failedModelPath;

    // Separate from LocalLlmExplanationProvider's FindModelPath — this provider is built against
    // the raw base model, not whatever fine-tune LocalAiModelCatalog's selected option points to.
    // TODO(temporary): hardcoded to the local test conversion while validating the tool loop itself
    // — swap to modelService.FindModelPath("qwen2.5-1.5b-base") once that catalog entry is hosted.
    public string? FindModelPath() =>
        File.Exists(TempTestModelPath) ? TempTestModelPath : modelService.FindModelPath("qwen2.5-1.5b-base");

    private const string TempTestModelPath = "G:/Users/Urakka/AppData/Local/Temp/qwen25-base-Q4_K_M.gguf";

    public async Task<RulesGeneratedAnswer> AnswerAsync(string question, CancellationToken ct = default)
    {
        if (!settings.IsEnabled())
            return new RulesGeneratedAnswer(null, false, "Local AI explanations are turned off.");
        var modelPath = FindModelPath();
        if (modelPath is null)
            return new RulesGeneratedAnswer(null, false, "The tool-agent base model hasn't been downloaded yet.");

        await _gate.WaitAsync(ct);
        try
        {
            if (!EnsureWeightsLoaded(modelPath))
                return new RulesGeneratedAnswer(null, false, "Could not load the tool-agent base model.");

            using var requestContext = _weights!.CreateContext(_modelParams!);
            var executor = new InteractiveExecutor(requestContext);
            var chatHistory = new ChatHistory();
            chatHistory.AddMessage(AuthorRole.System, SystemPrompt);
            var session = new ChatSession(executor, chatHistory)
                .WithHistoryTransform(new PromptTemplateTransformer(_weights!, withAssistant: true));

            var nextMessage = $"Question: {question}";
            const int maxToolRounds = 4;
            for (var round = 0; round <= maxToolRounds; round++)
            {
                var inferenceParams = new InferenceParams
                {
                    MaxTokens = 400,
                    AntiPrompts = ["User:", "<|im_end|>"],
                    SamplingPipeline = new DefaultSamplingPipeline
                    {
                        Temperature = 0.15f,
                        RepeatPenalty = 1.1f,
                        // Real testing caught this model skipping tool use entirely and answering
                        // from generic outside-game knowledge on the very first turn, ignoring the
                        // system prompt's explicit "you must use tools" instruction outright — the
                        // same instruction-following gap that (in the opposite direction) made the
                        // fine-tuned model ignore tool-call instructions completely. Forcing round 0's
                        // grammar to ONLY accept the tool-call shape makes skipping it structurally
                        // impossible rather than merely discouraged: at least one real lookup happens
                        // before the model can ever produce free-form text. Later rounds go back to
                        // unconstrained sampling once real grounding is already in context.
                        Grammar = round == 0 ? new Grammar(ForcedToolCallGrammar, "root") : null,
                    },
                    OverflowStrategy = LLama.Common.ContextOverflowStrategy.TruncateAndReprefill,
                };

                var output = new StringBuilder();
                await foreach (var token in session.ChatAsync(new ChatHistory.Message(AuthorRole.User, nextMessage), inferenceParams)
                    .WithCancellation(ct))
                    output.Append(token);

                var raw = StripLeadingThinkBlock(output.ToString());
                var toolCall = ExtractToolCall(raw);
                logger.LogDebug("Ask Rules (tools): round {Round} calledTool={CalledTool} raw={Raw}", round, toolCall is not null, raw);

                if (toolCall is null)
                {
                    var final = StripTrailingAntiPrompt(raw, inferenceParams.AntiPrompts);
                    return final.Length == 0
                        ? new RulesGeneratedAnswer(null, false, "The tool-agent model returned an empty response.")
                        : new RulesGeneratedAnswer(final, true, null);
                }

                if (round == maxToolRounds)
                {
                    logger.LogDebug("Ask Rules (tools): hit max tool-call rounds without a final answer");
                    return new RulesGeneratedAnswer(null, false, "The tool-agent model didn't reach a final answer in time.");
                }

                var (name, arguments) = toolCall.Value;
                var result = await RunToolAsync(name, arguments, ct);
                logger.LogDebug("Ask Rules (tools): {Name}({Arguments}) -> {Result}", name, arguments, Cap(result, 300));
                // No native "tool" role in LLamaSharp's AuthorRole (only System/User/Assistant) even
                // though the underlying chat template has one — approximated as a clearly-delimited
                // User turn instead. The system prompt primes the model for this shape specifically.
                nextMessage = $"<tool_response>\n{result}\n</tool_response>";
            }

            return new RulesGeneratedAnswer(null, false, "The tool-agent model didn't reach a final answer in time.");
        }
        catch (Exception ex)
        {
            logger.LogWarning(ex, "Tool-agent explanation failed");
            return new RulesGeneratedAnswer(null, false, ex.Message);
        }
        finally
        {
            _gate.Release();
        }
    }

    // Creates a DI scope per tool call rather than injecting AppDbContext/CardCacheService/
    // RulesSearchService/CardTextSymbolCatalogService directly — those are all Scoped (EF Core's own
    // default, matched by the services built on it), and this provider is a Singleton so its model
    // weights stay resident across requests. A Singleton can't hold a Scoped dependency directly
    // (DI throws at startup); creating a fresh scope per call is the standard fix, and also means
    // each tool call sees a clean, uncached DbContext rather than one accumulating state across an
    // entire process lifetime.
    private async Task<string> RunToolAsync(string name, Dictionary<string, string> arguments, CancellationToken ct)
    {
        using var scope = scopeFactory.CreateScope();
        switch (name)
        {
            case "search_rules":
                if (!arguments.TryGetValue("query", out var query) || string.IsNullOrWhiteSpace(query))
                    return "Error: search_rules requires a non-empty \"query\" argument.";
                return await SearchRulesToolAsync(scope.ServiceProvider, query, ct);
            case "search_cards":
                if (!arguments.TryGetValue("name", out var cardName) || string.IsNullOrWhiteSpace(cardName))
                    return "Error: search_cards requires a non-empty \"name\" argument.";
                return await SearchCardsToolAsync(scope.ServiceProvider, cardName, ct);
            default:
                return $"Error: unknown tool \"{name}\". Available tools: search_rules, search_cards.";
        }
    }

    private static async Task<string> SearchRulesToolAsync(IServiceProvider sp, string query, CancellationToken ct)
    {
        var search = sp.GetRequiredService<RulesSearchService>();
        // Real testing caught the model improvising SQL/FTS-style wildcards ("*Hunt*") the tool
        // description never mentioned — RulesSearchService.SearchAsync's exact-keyword fast path
        // (RulesKeywordCatalogService.Normalize) doesn't recognize a wildcard-wrapped term as the
        // keyword it actually is, so it fell through to plain FTS and returned the wrong rule (one
        // that only happened to mention "the Hunt" inside a card-name example, not the real Hunt
        // keyword definition). Stripping stray wildcard characters before searching is a defensive,
        // input-side fix that doesn't depend on the model's query phrasing being clean.
        var cleaned = query.Trim().Trim('*', '%', '"');
        var response = await search.SearchAsync(cleaned, currentOnly: true, limit: 5, ct);
        if (response.Results.Count == 0) return $"No rules found matching \"{cleaned}\".";
        var parts = response.Results.Select(hit =>
        {
            var label = hit.RuleNumber is not null ? $"Rule {hit.RuleNumber}" : hit.Title;
            return $"[{label}] ({hit.Document.Authority})\n{Cap(hit.FullText, 1200)}";
        });
        return string.Join("\n\n", parts);
    }

    private static async Task<string> SearchCardsToolAsync(IServiceProvider sp, string name, CancellationToken ct)
    {
        var cards = sp.GetRequiredService<CardCacheService>();
        var symbols = sp.GetRequiredService<CardTextSymbolCatalogService>();
        var db = sp.GetRequiredService<AppDbContext>();
        var matches = await cards.FindByNameAsync(name, ct);
        if (matches.Count == 0) return $"No card found named \"{name}\".";
        var card = matches[0];
        var parts = new List<string>();
        if (!string.IsNullOrWhiteSpace(card.TextPlain))
            parts.Add($"{card.Name}'s printed text: \"{await symbols.HumanizeAsync(card.TextPlain, ct)}\"");
        var legalities = await db.CardLegalities.Where(l => l.CardId == card.Id && l.IsCurrent).ToListAsync(ct);
        parts.AddRange(legalities.Select(l => $"{card.Name} is {l.Status} in {l.Format}."));
        var errata = await db.CardErrata.Where(e => e.CardId == card.Id && e.IsCurrent).ToListAsync(ct);
        parts.AddRange(errata.Select(e => $"{card.Name} errata — original: \"{e.OriginalText}\", updated: \"{e.CorrectedText}\""));
        return parts.Count > 0 ? string.Join("\n", parts) : $"{card.Name} has no printed text, legality, or errata on file.";
    }

    // Scans for a balanced JSON object after "<tool_call>" rather than regex-matching up to
    // "</tool_call>" — real generation observed during probing cut off (hit MaxTokens/an anti-prompt)
    // before ever emitting the closing tag, even though the JSON payload itself was already complete
    // and well-formed. A brace-balance scan finds the real end of the object regardless of whether
    // the closing tag ever arrives.
    private static (string Name, Dictionary<string, string> Arguments)? ExtractToolCall(string text)
    {
        var start = text.IndexOf("<tool_call>", StringComparison.Ordinal);
        if (start < 0) return null;
        var jsonStart = start + "<tool_call>".Length;
        var depth = 0;
        var end = -1;
        for (var i = jsonStart; i < text.Length; i++)
        {
            if (text[i] == '{') depth++;
            else if (text[i] == '}')
            {
                depth--;
                if (depth == 0) { end = i; break; }
            }
        }
        if (end < 0) return null;
        var jsonText = text[jsonStart..(end + 1)].Trim();
        try
        {
            using var doc = JsonDocument.Parse(jsonText);
            var root = doc.RootElement;
            if (!root.TryGetProperty("name", out var nameProp) || nameProp.ValueKind != JsonValueKind.String)
                return null;
            var args = new Dictionary<string, string>();
            if (root.TryGetProperty("arguments", out var argsProp) && argsProp.ValueKind == JsonValueKind.Object)
                foreach (var prop in argsProp.EnumerateObject())
                    args[prop.Name] = prop.Value.ValueKind == JsonValueKind.String ? prop.Value.GetString()! : prop.Value.GetRawText();
            return (nameProp.GetString()!, args);
        }
        catch (JsonException)
        {
            return null;
        }
    }

    private bool EnsureWeightsLoaded(string modelPath)
    {
        if (_weights is not null && _loadedModelPath == modelPath) return true;
        if (_weights is not null) { _weights.Dispose(); _weights = null; }
        try
        {
            _modelParams = new ModelParams(modelPath) { ContextSize = 6144, GpuLayerCount = 0 };
            _weights = LLamaWeights.LoadFromFile(_modelParams);
            _loadedModelPath = modelPath;
            _failedModelPath = null;
            return true;
        }
        catch (Exception ex)
        {
            logger.LogWarning(ex, "Failed to load tool-agent base model from {Path}", modelPath);
            _failedModelPath = modelPath;
            return false;
        }
    }

    private static string StripLeadingThinkBlock(string text)
    {
        var trimmed = text.TrimStart();
        if (!trimmed.StartsWith("<think>", StringComparison.Ordinal)) return text;
        var closeIndex = trimmed.IndexOf("</think>", StringComparison.Ordinal);
        if (closeIndex >= 0) return trimmed[(closeIndex + "</think>".Length)..].TrimStart();
        return trimmed["<think>".Length..].TrimStart();
    }

    private static string StripTrailingAntiPrompt(string text, IEnumerable<string> antiPrompts)
    {
        var trimmed = text;
        foreach (var antiPrompt in antiPrompts)
        {
            var index = trimmed.IndexOf(antiPrompt, StringComparison.Ordinal);
            if (index >= 0) trimmed = trimmed[..index];
        }
        return trimmed.Trim();
    }

    private static string Cap(string text, int maxChars) =>
        text.Length > maxChars ? text[..maxChars] + "…" : text;

    public void Dispose()
    {
        _weights?.Dispose();
        _gate.Dispose();
    }
}
