// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RiftBoundTracker.App.Data;

#nullable disable

namespace RiftBoundTracker.App.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260824013351_AddHologramCount")]
    partial class AddHologramCount
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("RiftBoundTracker.App.Data.CardEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Artist")
                        .HasColumnType("TEXT");

                    b.Property<int>("BinderCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CachedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CollectorCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CollectorNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DomainsCsv")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Energy")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Flavour")
                        .HasColumnType("TEXT");

                    b.Property<int>("HologramCount")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("ImageHash")
                        .HasColumnType("BLOB");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSyntheticToken")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LocalImagePath")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Might")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Orientation")
                        .HasColumnType("TEXT");

                    b.Property<int>("OwnedCount")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Power")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Rarity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SetId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SetLabel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Supertype")
                        .HasColumnType("TEXT");

                    b.Property<string>("TcgplayerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TextPlain")
                        .HasColumnType("TEXT");

                    b.Property<string>("TextRich")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BinderCount");

                    b.HasIndex("CollectorNumber");

                    b.HasIndex("IsFavorite");

                    b.HasIndex("SetId");

                    b.HasIndex("SetId", "CollectorNumber");

                    b.ToTable("Cards");
                });

            modelBuilder.Entity("RiftBoundTracker.App.Data.CardErrataEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CardId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CardNameRaw")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrectedText")
                        .HasColumnType("TEXT");

                    b.Property<int>("DocumentId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("EffectiveAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OriginalText")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.HasIndex("DocumentId");

                    b.ToTable("CardErrata");
                });

            modelBuilder.Entity("RiftBoundTracker.App.Data.CardLegalityEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CardId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CardNameRaw")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DocumentId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("EffectiveAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.HasIndex("CardId", "Format");

                    b.ToTable("CardLegalities");
                });

            modelBuilder.Entity("RiftBoundTracker.App.Data.CardRuleReferenceEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CardId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("KeywordId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("KeywordId");

                    b.HasIndex("CardId", "KeywordId")
                        .IsUnique();

                    b.ToTable("CardRuleReferences");
                });

            modelBuilder.Entity("RiftBoundTracker.App.Data.CardTextSymbolEntity", b =>
                {
                    b.Property<string>("Token")
                        .HasColumnType("TEXT");

                    b.Property<string>("AssetPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("BackgroundColor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BorderColor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ForegroundColor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Shape")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Token");

                    b.HasIndex("Kind", "SortOrder");

                    b.ToTable("CardTextSymbols");
                });

            modelBuilder.Entity("RiftBoundTracker.App.Data.CommunityDeckCardEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CardId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CommunityDeckId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.HasIndex("CommunityDeckId", "CardId");

                    b.ToTable("CommunityDeckCards");
                });

            modelBuilder.Entity("RiftBoundTracker.App.Data.CommunityDeckEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("ImportedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LegendCardId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LegendRawName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Standing")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TournamentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LegendCardId");

                    b.HasIndex("TournamentId");

                    b.ToTable("CommunityDecks");
                });

            modelBuilder.Entity("RiftBoundTracker.App.Data.CommunitySyncStateEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DeckCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastError")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastSyncAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("LastSyncOk")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TournamentCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UnresolvedCardCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("CommunitySyncState");
                });

            modelBuilder.Entity("RiftBoundTracker.App.Data.CommunityTournamentEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExternalTournamentId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ImportedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ParticipantCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("StartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExternalTournamentId")
                        .IsUnique();

                    b.HasIndex("StartDate");

                    b.ToTable("CommunityTournaments");
                });

            modelBuilder.Entity("RiftBoundTracker.App.Data.DeckCardEntity", b =>
                {
                    b.Property<int>("DeckId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CardId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Section")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("DeckId", "CardId", "Section");

                    b.HasIndex("CardId");

                    b.ToTable("DeckCards");
                });

            modelBuilder.Entity("RiftBoundTracker.App.Data.DeckEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CoverCardId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UpdatedAt");

                    b.ToTable("Decks");
                });

            modelBuilder.Entity("RiftBoundTracker.App.Data.PriceQueueEntity", b =>
                {
                    b.Property<string>("CardId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("QueuedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("CardId");

                    b.HasIndex("QueuedAt");

                    b.ToTable("PriceQueue");
                });

            modelBuilder.Entity("RiftBoundTracker.App.Data.PriceSnapshotEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CapturedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CardId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("Change24Hours")
                        .HasColumnType("REAL");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("MarketPrice")
                        .HasColumnType("REAL");

                    b.Property<string>("Printing")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("SourceUpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("VariantId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CardId", "CapturedAt");

                    b.HasIndex("CardId", "Provider", "VariantId", "CapturedAt");

                    b.ToTable("PriceSnapshots");
                });

            modelBuilder.Entity("RiftBoundTracker.App.Data.RuleConceptEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique();

                    b.ToTable("RuleConcepts");
                });

            modelBuilder.Entity("RiftBoundTracker.App.Data.RuleConceptKeywordEntity", b =>
                {
                    b.Property<int>("ConceptId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("KeywordId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ConceptId", "KeywordId");

                    b.HasIndex("KeywordId");

                    b.ToTable("RuleConceptKeywords");
                });

            modelBuilder.Entity("RiftBoundTracker.App.Data.RuleConceptPhraseEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConceptId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NormalizedPhrase")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phrase")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ConceptId");

                    b.HasIndex("NormalizedPhrase");

                    b.ToTable("RuleConceptPhrases");
                });

            modelBuilder.Entity("RiftBoundTracker.App.Data.RuleCrossReferenceEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FromRuleId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReferenceText")
                        .HasColumnType("TEXT");

                    b.Property<int>("ToRuleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ToRuleId");

                    b.HasIndex("FromRuleId", "ToRuleId")
                        .IsUnique();

                    b.ToTable("RuleCrossReferences");
                });

            modelBuilder.Entity("RiftBoundTracker.App.Data.RuleDocumentEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Authority")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentHash")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("DiscoveredAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DocumentVersion")
                        .HasColumnType("TEXT");

                    b.Property<string>("DownloadUrl")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DownloadedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastError")
                        .HasColumnType("TEXT");

                    b.Property<string>("ParseStatus")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("SourceType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SourceType", "IsCurrent");

                    b.ToTable("RuleDocuments");
                });

            modelBuilder.Entity("RiftBoundTracker.App.Data.RuleEntryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Authority")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DocumentId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ParentRuleId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RuleNumber")
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ParentRuleId");

                    b.HasIndex("RuleNumber");

                    b.HasIndex("DocumentId", "SortOrder");

                    b.ToTable("RuleEntries");
                });

            modelBuilder.Entity("RiftBoundTracker.App.Data.RuleEntryKeywordEntity", b =>
                {
                    b.Property<int>("RuleEntryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("KeywordId")
                        .HasColumnType("INTEGER");

                    b.HasKey("RuleEntryId", "KeywordId");

                    b.HasIndex("KeywordId");

                    b.ToTable("RuleEntryKeywords");
                });

            modelBuilder.Entity("RiftBoundTracker.App.Data.RuleKeywordAliasEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("KeywordId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NormalizedAlias")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("KeywordId");

                    b.HasIndex("NormalizedAlias");

                    b.ToTable("RuleKeywordAliases");
                });

            modelBuilder.Entity("RiftBoundTracker.App.Data.RuleKeywordEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CanonicalRuleId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<string>("Definition")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsOfficialKeyword")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CanonicalRuleId");

                    b.HasIndex("NormalizedName")
                        .IsUnique();

                    b.ToTable("RuleKeywords");
                });

            modelBuilder.Entity("RiftBoundTracker.App.Data.RulesSyncStateEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DocumentsIndexed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ErrataIndexed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("KeywordsIndexed")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LastCheckAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastError")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastSuccessfulSyncAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("LastSyncOk")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LegalityEntriesIndexed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RulesIndexed")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("RulesSyncState");
                });

            modelBuilder.Entity("RiftBoundTracker.App.Data.SyncStateEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CatalogContentRevision")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LastFullSyncAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("LastFullSyncOk")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalCardsSynced")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalSetsKnown")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("SyncState");
                });

            modelBuilder.Entity("RiftBoundTracker.App.Data.CardErrataEntity", b =>
                {
                    b.HasOne("RiftBoundTracker.App.Data.CardEntity", "Card")
                        .WithMany()
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("RiftBoundTracker.App.Data.RuleDocumentEntity", "Document")
                        .WithMany()
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");

                    b.Navigation("Document");
                });

            modelBuilder.Entity("RiftBoundTracker.App.Data.CardLegalityEntity", b =>
                {
                    b.HasOne("RiftBoundTracker.App.Data.CardEntity", "Card")
                        .WithMany()
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("RiftBoundTracker.App.Data.RuleDocumentEntity", "Document")
                        .WithMany()
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");

                    b.Navigation("Document");
                });

            modelBuilder.Entity("RiftBoundTracker.App.Data.CardRuleReferenceEntity", b =>
                {
                    b.HasOne("RiftBoundTracker.App.Data.CardEntity", "Card")
                        .WithMany()
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RiftBoundTracker.App.Data.RuleKeywordEntity", "Keyword")
                        .WithMany()
                        .HasForeignKey("KeywordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");

                    b.Navigation("Keyword");
                });

            modelBuilder.Entity("RiftBoundTracker.App.Data.CommunityDeckCardEntity", b =>
                {
                    b.HasOne("RiftBoundTracker.App.Data.CardEntity", "Card")
                        .WithMany()
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RiftBoundTracker.App.Data.CommunityDeckEntity", "CommunityDeck")
                        .WithMany("Cards")
                        .HasForeignKey("CommunityDeckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");

                    b.Navigation("CommunityDeck");
                });

            modelBuilder.Entity("RiftBoundTracker.App.Data.CommunityDeckEntity", b =>
                {
                    b.HasOne("RiftBoundTracker.App.Data.CardEntity", "LegendCard")
                        .WithMany()
                        .HasForeignKey("LegendCardId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RiftBoundTracker.App.Data.CommunityTournamentEntity", "Tournament")
                        .WithMany("Decks")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LegendCard");

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("RiftBoundTracker.App.Data.DeckCardEntity", b =>
                {
                    b.HasOne("RiftBoundTracker.App.Data.CardEntity", "Card")
                        .WithMany("DeckCards")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RiftBoundTracker.App.Data.DeckEntity", "Deck")
                        .WithMany("Cards")
                        .HasForeignKey("DeckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");

                    b.Navigation("Deck");
                });

            modelBuilder.Entity("RiftBoundTracker.App.Data.PriceQueueEntity", b =>
                {
                    b.HasOne("RiftBoundTracker.App.Data.CardEntity", "Card")
                        .WithOne("PriceQueueItem")
                        .HasForeignKey("RiftBoundTracker.App.Data.PriceQueueEntity", "CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");
                });

            modelBuilder.Entity("RiftBoundTracker.App.Data.PriceSnapshotEntity", b =>
                {
                    b.HasOne("RiftBoundTracker.App.Data.CardEntity", "Card")
                        .WithMany("PriceSnapshots")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");
                });

            modelBuilder.Entity("RiftBoundTracker.App.Data.RuleConceptKeywordEntity", b =>
                {
                    b.HasOne("RiftBoundTracker.App.Data.RuleConceptEntity", "Concept")
                        .WithMany("Keywords")
                        .HasForeignKey("ConceptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RiftBoundTracker.App.Data.RuleKeywordEntity", "Keyword")
                        .WithMany()
                        .HasForeignKey("KeywordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Concept");

                    b.Navigation("Keyword");
                });

            modelBuilder.Entity("RiftBoundTracker.App.Data.RuleConceptPhraseEntity", b =>
                {
                    b.HasOne("RiftBoundTracker.App.Data.RuleConceptEntity", "Concept")
                        .WithMany("Phrases")
                        .HasForeignKey("ConceptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Concept");
                });

            modelBuilder.Entity("RiftBoundTracker.App.Data.RuleCrossReferenceEntity", b =>
                {
                    b.HasOne("RiftBoundTracker.App.Data.RuleEntryEntity", "FromRule")
                        .WithMany()
                        .HasForeignKey("FromRuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RiftBoundTracker.App.Data.RuleEntryEntity", "ToRule")
                        .WithMany()
                        .HasForeignKey("ToRuleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FromRule");

                    b.Navigation("ToRule");
                });

            modelBuilder.Entity("RiftBoundTracker.App.Data.RuleEntryEntity", b =>
                {
                    b.HasOne("RiftBoundTracker.App.Data.RuleDocumentEntity", "Document")
                        .WithMany("Entries")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RiftBoundTracker.App.Data.RuleEntryEntity", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentRuleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Document");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("RiftBoundTracker.App.Data.RuleEntryKeywordEntity", b =>
                {
                    b.HasOne("RiftBoundTracker.App.Data.RuleKeywordEntity", "Keyword")
                        .WithMany("RuleEntries")
                        .HasForeignKey("KeywordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RiftBoundTracker.App.Data.RuleEntryEntity", "RuleEntry")
                        .WithMany("Keywords")
                        .HasForeignKey("RuleEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Keyword");

                    b.Navigation("RuleEntry");
                });

            modelBuilder.Entity("RiftBoundTracker.App.Data.RuleKeywordAliasEntity", b =>
                {
                    b.HasOne("RiftBoundTracker.App.Data.RuleKeywordEntity", "Keyword")
                        .WithMany("Aliases")
                        .HasForeignKey("KeywordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Keyword");
                });

            modelBuilder.Entity("RiftBoundTracker.App.Data.RuleKeywordEntity", b =>
                {
                    b.HasOne("RiftBoundTracker.App.Data.RuleEntryEntity", "CanonicalRule")
                        .WithMany()
                        .HasForeignKey("CanonicalRuleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CanonicalRule");
                });

            modelBuilder.Entity("RiftBoundTracker.App.Data.CardEntity", b =>
                {
                    b.Navigation("DeckCards");

                    b.Navigation("PriceQueueItem");

                    b.Navigation("PriceSnapshots");
                });

            modelBuilder.Entity("RiftBoundTracker.App.Data.CommunityDeckEntity", b =>
                {
                    b.Navigation("Cards");
                });

            modelBuilder.Entity("RiftBoundTracker.App.Data.CommunityTournamentEntity", b =>
                {
                    b.Navigation("Decks");
                });

            modelBuilder.Entity("RiftBoundTracker.App.Data.DeckEntity", b =>
                {
                    b.Navigation("Cards");
                });

            modelBuilder.Entity("RiftBoundTracker.App.Data.RuleConceptEntity", b =>
                {
                    b.Navigation("Keywords");

                    b.Navigation("Phrases");
                });

            modelBuilder.Entity("RiftBoundTracker.App.Data.RuleDocumentEntity", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("RiftBoundTracker.App.Data.RuleEntryEntity", b =>
                {
                    b.Navigation("Keywords");
                });

            modelBuilder.Entity("RiftBoundTracker.App.Data.RuleKeywordEntity", b =>
                {
                    b.Navigation("Aliases");

                    b.Navigation("RuleEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
