// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RiftBoundTracker.App.Data;

#nullable disable

namespace RiftBoundTracker.App.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260814030854_AddPriceQueue")]
    partial class AddPriceQueue
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("RiftBoundTracker.App.Data.CardEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Artist")
                        .HasColumnType("TEXT");

                    b.Property<int>("BinderCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CachedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CollectorCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CollectorNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DomainsCsv")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Energy")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Flavour")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("ImageHash")
                        .HasColumnType("BLOB");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LocalImagePath")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Might")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Orientation")
                        .HasColumnType("TEXT");

                    b.Property<int>("OwnedCount")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Power")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Rarity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SetId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SetLabel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Supertype")
                        .HasColumnType("TEXT");

                    b.Property<string>("TcgplayerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TextPlain")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BinderCount");

                    b.HasIndex("CollectorNumber");

                    b.HasIndex("IsFavorite");

                    b.HasIndex("SetId");

                    b.HasIndex("SetId", "CollectorNumber");

                    b.ToTable("Cards");
                });

            modelBuilder.Entity("RiftBoundTracker.App.Data.DeckCardEntity", b =>
                {
                    b.Property<int>("DeckId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CardId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Section")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("DeckId", "CardId", "Section");

                    b.HasIndex("CardId");

                    b.ToTable("DeckCards");
                });

            modelBuilder.Entity("RiftBoundTracker.App.Data.DeckEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CoverCardId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UpdatedAt");

                    b.ToTable("Decks");
                });

            modelBuilder.Entity("RiftBoundTracker.App.Data.PriceQueueEntity", b =>
                {
                    b.Property<string>("CardId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("QueuedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("CardId");

                    b.HasIndex("QueuedAt");

                    b.ToTable("PriceQueue");
                });

            modelBuilder.Entity("RiftBoundTracker.App.Data.PriceSnapshotEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CapturedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CardId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("Change24Hours")
                        .HasColumnType("REAL");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("MarketPrice")
                        .HasColumnType("REAL");

                    b.Property<string>("Printing")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("SourceUpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("VariantId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CardId", "CapturedAt");

                    b.HasIndex("CardId", "Provider", "VariantId", "CapturedAt");

                    b.ToTable("PriceSnapshots");
                });

            modelBuilder.Entity("RiftBoundTracker.App.Data.SyncStateEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LastFullSyncAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("LastFullSyncOk")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalCardsSynced")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalSetsKnown")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("SyncState");
                });

            modelBuilder.Entity("RiftBoundTracker.App.Data.DeckCardEntity", b =>
                {
                    b.HasOne("RiftBoundTracker.App.Data.CardEntity", "Card")
                        .WithMany("DeckCards")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RiftBoundTracker.App.Data.DeckEntity", "Deck")
                        .WithMany("Cards")
                        .HasForeignKey("DeckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");

                    b.Navigation("Deck");
                });

            modelBuilder.Entity("RiftBoundTracker.App.Data.PriceQueueEntity", b =>
                {
                    b.HasOne("RiftBoundTracker.App.Data.CardEntity", "Card")
                        .WithOne("PriceQueueItem")
                        .HasForeignKey("RiftBoundTracker.App.Data.PriceQueueEntity", "CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");
                });

            modelBuilder.Entity("RiftBoundTracker.App.Data.PriceSnapshotEntity", b =>
                {
                    b.HasOne("RiftBoundTracker.App.Data.CardEntity", "Card")
                        .WithMany("PriceSnapshots")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");
                });

            modelBuilder.Entity("RiftBoundTracker.App.Data.CardEntity", b =>
                {
                    b.Navigation("DeckCards");

                    b.Navigation("PriceQueueItem");

                    b.Navigation("PriceSnapshots");
                });

            modelBuilder.Entity("RiftBoundTracker.App.Data.DeckEntity", b =>
                {
                    b.Navigation("Cards");
                });
#pragma warning restore 612, 618
        }
    }
}
