// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RiftBoundTracker.App.Data;

#nullable disable

namespace RiftBoundTracker.App.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("RiftBoundTracker.App.Data.CardEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Artist")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CachedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CollectorNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DomainsCsv")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Energy")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Flavour")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("ImageHash")
                        .HasColumnType("BLOB");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LocalImagePath")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Might")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Orientation")
                        .HasColumnType("TEXT");

                    b.Property<int>("OwnedCount")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Power")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Rarity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SetId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SetLabel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Supertype")
                        .HasColumnType("TEXT");

                    b.Property<string>("TcgplayerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TextPlain")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CollectorNumber");

                    b.HasIndex("SetId");

                    b.HasIndex("SetId", "CollectorNumber");

                    b.ToTable("Cards");
                });
#pragma warning restore 612, 618
        }
    }
}
